server:
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/workshop-todo
    username: root
    password: my-secret-pw

  jpa:
    hibernate:
      ddl-auto: update
